### ISSUE TITLE
Can't get file logging to work

### ISSUE THREAD

**Issue by MrPrezident** [vrpn/vrpn#102]
I'm trying to add logging to text receiver.  I cannot get it to work.  When I do this everything works fine:

``` cpp
dev->text = new vrpn_Text_Receiver(dev->name);
```

but when I add logfiles like this it doesn't work:

``` cpp
char *local_in_log = new char [30];
char *local_out_log = new char [30];
char *remote_in_log = new char [30];
char *remote_out_log = new char [30];
sprintf(local_in_log, "logs%d/local_in.%s.log", log_num, argv[i]);
sprintf(local_out_log, "logs%d/local_out.%s.log", log_num, argv[i]);
sprintf(remote_in_log, "logs%d/remote_in.%s.log", log_num, argv[i]);
sprintf(remote_out_log, "logs%d/remote_out.%s.log", log_num, argv[i]);
vrpn_Connection *c = vrpn_get_connection_by_name(station_name, local_in_log, local_out_log, remote_in_log, remote_out_log);
dev->text = new vrpn_Text_Receiver(dev->name, c);
```

specifically, I get these messages:

```
vrpn_Endpoint::handle_tcp_messages:  Can't read header (this is normal when a connection is dropped)
vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)
VRPN Warning
 (4) from Juggler: No response from server for >= 3 seconds
```

**Comment by russell-taylor** [comment]
One thing I notice is that the names include directories in them, which presumably will not have been created ahead of time.  The open() system call does not create intermediate directories along the way, so the files won't get created.

The second thing is that you probably want to pass dev->name into vrpn_get_connection_by_name rather than station_name. It should parse it correctly to pull out the station name to keep you from having to fill it in.

The test_logging program does a variety of log file storage and reloading, so should be a good example of how to get this working.  I just tested it from the master on Windows 8.1 and it worked.

For replaying data from the log files, you should replace the things after the @ sign with the file name... @localhost becomes @file:my_file_name

**Comment by russell-taylor** [comment]
This was last updated a while ago, so I'm going to assume that the suggested fixes worked and close the issue.  If not, go ahead and reopen it.
