### ISSUE TITLE
Xkeys controller no longer works on Windows 8.1 after recent HIDAPI update

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#138]
This is for a 68-key device that worked using the holder version of the HIDAPI before the update.

The server reports:

vrpn_HidInterface::reconnect(): Could not open device \\?\hid#vid_05f3&pid_045a&mi_02#7&39688f45&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

**Comment by russell-taylor** [comment]
It does work when run as sudo on a mac.

**Comment by russell-taylor** [comment]
Also works under Ubuntu Linux when run as sudo.

Looks like the problem is only under Windows, but is new since the change of hidapi.

**Comment by rpavlik** [comment]
Does the xkeys thing show up as a keyboard as well, or just as a custom device?

**Comment by rpavlik** [comment]
I emailed you a build of the latest master with a HIDAPI build that included this patch which should give us more information than the server is telling us https://github.com/vrpn/hidapi/commit/961ef76f96803826f4693fae17237c104ca30538

**Comment by russell-taylor** [comment]
It shows up as a keyboard.

When run from the verbose zip file as a normal user or when running the -v shortcut as admin, or when running the vrpn_server.exe as administrator, I get the following:

Reading from config file vrpn.cfg
HIDAPI error in open_device with path \\?\hid#vid_05f3&pid_045a&mi_02#7&39688f45
&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: Access is denied.

vrpn_HidInterface::reconnect(): Could not open device \\?\hid#vid_05f3&pid_045a&
mi_02#7&39688f45&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
vrpn_HidInterface::send_data(): Interface not currently working
vrpn_HidInterface::send_data(): Interface not currently working
Opening vrpn_Xkeys_Jog_And_Shuttle68 xkeys0

**Comment by rpavlik** [comment]
Ah, OK, so that explains it. Windows likes to have exclusive access to keyboards first, apparently - seems like these might be related:
- https://github.com/signal11/hidapi/pull/44
- https://gist.github.com/cactrot/7242364

I'll have to look at how exactly the xkeys vrpn devices are interacting with the hid devices, and see if I can figure out a better, additional fallback case.

**Comment by rpavlik** [comment]
(or may also be related to this: https://github.com/signal11/hidapi/issues/247 - as I don't have a device, I don't know for sure)

**Comment by rpavlik** [comment]
Does this do anything for ya? I'd suspect not, since I think it to be similar, if a bit more rash, to the patch I put in our version, but maybe look into it: https://github.com/signal11/hidapi/commit/b5b2e1779b6cd2edda3066bbbf0921a2d6b1c3c0

cf https://github.com/signal11/hidapi/issues/231#issuecomment-191826232

**Comment by russell-taylor** [comment]
Bingo!  Changing that got it working.  Lights show when connection happens, can read results from it, the whole works.  It would be great if you can pull that patch in.

**Comment by rpavlik** [comment]
Weird. It didn't like the "reasonable" approach. OK, well, upstream took the dramatic approach, and presumably our fork must have been similar at some point if it worked, so this should be an easy enough change.
