### ISSUE TITLE
Xbox Controller not working on vrpn_server 

### ISSUE THREAD

**Issue by rctheriot** [vrpn/vrpn#172]
I've be able to start the vrpn_server with the mouse and keyboard by removing the comments on the following lines. I also tested that the server was working by using the vrpn_print_devices. 
# vrpn_Mouse Mouse0
# vrpn_Keyboard  Keyboard0

Once I remove the comments from the line below, the application vrpn_server crashes immediately on startup.
# vrpn_XInputGamepad XInput0 0

**Comment by russell-taylor** [comment]
Since the keyboard and mouse worked, I'm guessing you're on Linux.  The XInput code should only compile on Windows -- not good that it crashes on Linux, of course.  Just to make sure it works on Windows, I plugged an XBoxx 360 controller in and uncommented the vrpn_XInputGamepad line from vrpn.cfg and it opened fine on Windows 10, compiled using Visual Studio 2013 64-bit.

To talk with the XBox360 on Linux, you'll need to use the Joylin interface because it intercepts the device USB stream and does not pass it on to other drivers.

On Windows, you might want to try the vrpn_Microsoft_Controller_Raw_Xbox_S or vrpn_Microsoft_Controller_Raw_Xbox_360.

If these don't work for you, please specify the OS, compiler, and what libraries were found by CMake (path to DirectInput, for example).
