### ISSUE TITLE
cmake 3.5.1 on ubuntu 16.04 fails to install vrpn_python correctly

### ISSUE THREAD

**Issue by ososinski** [vrpn/vrpn#175]
The troubleshooting suggests the use of cmake 2.8.4 instead of 2.6 as the solution, using cmake 3.5.1 the only installed component is vrpn.so, missing the actual python bindings.

The Makefile2 only contains:

```
# Directory level rules for directory python_vrpn

# Convenience name for "all" pass in the directory.
python_vrpn/all:

.PHONY : python_vrpn/all

# Convenience name for "clean" pass in the directory.
python_vrpn/clean:

.PHONY : python_vrpn/clean

# Convenience name for "preinstall" pass in the directory.
python_vrpn/preinstall:

.PHONY : python_vrpn/preinstall
```

meaning python_vrpn does not build at all

**Comment by ososinski** [comment]
seems the issue is related to the distinction between VRPN_BUILD_PYTHON,  VRPN_BUILD_PYTHON_HANDCODED_2X and VRPN_BUILD_PYTHON_HANDCODED_3X

cmake seems to set HANDCODED_3x and python_vrpn expects :VRPN_BUILD_PYTHON

```
../build/CMakeCache.txt:VRPN_BUILD_PYTHON:BOOL=OFF
../build/CMakeCache.txt:VRPN_BUILD_PYTHON_HANDCODED_2X:BOOL=OFF
../build/CMakeCache.txt:VRPN_BUILD_PYTHON_HANDCODED_3X:BOOL=ON
```

solution is to modify python_vrpn/CMakeLists.txt line 6 from:

```
-if(SWIG_FOUND AND PYTHONLIBS_FOUND AND VRPN_BUILD_PYTHON)
+if(SWIG_FOUND AND PYTHONLIBS_FOUND AND (VRPN_BUILD_PYTHON OR VRPN_BUILD_PYTHON_HANDCODED_2X OR VRPN_BUILD_PYTHON_HANDCODED_3X))
```

and line 40:
```
-	if(PYTHON_LIBRARY MATCHES "python(2.[0-9])")
+	if(PYTHON_LIBRARY MATCHES "python([23].[0-9])")
```
to make it use python 3.x 

It needs testing if the code is compatible with python3, so far gets it installed and running with 
```
 VRPN Warning
 (3) from Tracker0: No response from server for >= 3 seconds
```
on the default test

**Comment by russell-taylor** [comment]
Thanks for digging into this and letting us know about it.

There is a lot of confusion surrounding Python and VRPN because there are two different versions of Python wrappings -- a Swig-generated one that ends up in python_vrpn and a separate hand-written set that end up in python.  They are not used together or related to each other.  This is described a bit in the README.python file in the root directory.

I've modified the CMakeLists.txt in python_vrpn to support python libraries 2 and 3, taking your word on it that they at least compile under Python 3.  This is in commit 34b2adbf208689839914fb40200df0a79a1894d1
