### ISSUE TITLE
Polhemus Liberty's position updates limited to 10Hz (instead of 240Hz)

### ISSUE THREAD

**Issue by Nodragem** [vrpn/vrpn#182]
Hello, 

I am using the Polhemus Liberty with VRPN. I followed the instruction given in Polhemus' technical report to compile VRPN with Polhemus PDI, to find [here](ftp://ftp.polhemus.com/pub/TechNotes/Polhemus%20Technical%20Note%201401%20VRPN.pdf).

My problem is that the clients, (no matter if it is the print client provided in VRPN, or the client provided by Vizard's VRPN plug-in (Worldviz)), are collecting / displaying data at a rate of 10Hz. However, we would like to use the Polhemus natural rate, which is at a 240 or 120 Hz.

We already used VRPN with other devices, and we did not run into this problem.
Note also that we tried to use the command `-millisleep 0` and `-millisleep 1` without any difference.

Is it possible that there is something contained in the polhemus plug-in for VRPN that limits the rate of recording to 10Hz? how could we remove this limitation?

Thank you very much for your help.

**Comment by russell-taylor** [comment]
Both the standard and high-speed raw Liberty drivers have the ability to send arbitrary commands to the devices during initialization.  The Isotrak vrpn.cfg example shows how to do this.  It may be that one of the commands that can be sent to the tracker is the rate at which it should update.

There is a set_update_rate() method that applications can use to request a specific update rate from a tracker, but the Liberty drivers do not seem to handle this message and the vrpn_print_devices program does not call it so that is not the issue here.

The Liberty manual says that it can only be set at two update rates; 120 Hz or 240 Hz, using the 'R' command, so it doesn't seem like it can be getting set to operate internally at 10 Hz.

The LibertyHS drivers are both setting the trackers into continuous binary mode and then waiting for responses, so they should be reading as quickly as possible from the trackers.

Hmm... you said that you are using the PDI drivers to talk with the device.  I've not used those drivers.  It looks like indeed the mainloop() function throttles how rapidly it sends reports based on update_rate, which is set as one of the parameters in the constructor for the vrpn_tracker_G4.  This appears to default to 10 Hz and be settable by an additional parameter beyond the tracker name in the vrpn.cfg file.  The following line may do what you want:

vrpn_Tracker_G4	G4 240

**Comment by Nodragem** [comment]
Excellent,
I needed to use:
`vrpn_Tracker_Liberty MyName 240`
and it works!

Note: I did not measure whether it was working exactly at 240Hz though, 
I just know that it is faster than the refresh rate of my display monitor (60Hz).
