### ISSUE TITLE
Crash when i uses LeapMotion and Kinect on same server

### ISSUE THREAD

**Issue by klingerkrieg** [vrpn/vrpn#195]
I created a driver for LeapMotion and Kinect, but when i use:

```
if ( d_connection->pack_message(len, _timestamp, position_m_id, d_sender_id, msgbuf, vrpn_CONNECTION_LOW_LATENCY) ) {
	fprintf(stderr, "vrpn_LeapMotion: cannot write message: tossing\n");
}
```

Sometimes an error occurs in this line of the LeapMotion driver. I believe the server tries to send messages from both devices at the same time causing the conflict. This is because we could not catch this exception with try or __try. So I modified the class vrpn_Connection, if there is a better way to solve please let me know.

**Comment by klingerkrieg** [comment]
I have modified so that only one device sends a message at that moment:
```
bool vrpn_Connection::packInUse = false;

int vrpn_Connection::pack_message(vrpn_uint32 len, struct timeval time,
                                  vrpn_int32 type, vrpn_int32 sender,
                                  const char *buffer,
                                  vrpn_uint32 class_of_service)
{
    // all initial code
    // If this is not a system message, make sure the sender is legal.
    if (type >= 0) {
        if ((sender < 0) || (sender >= d_dispatcher->numSenders())) {
            printf("vrpn_Connection::pack_message: bad sender (%d)\n", sender);
            return -1;
        }
    }
    while ( packInUse ) {
	vrpn_SleepMsecs(1);
    }
	packInUse = true;
   // all code to send message
	packInUse = false;

    return ret;
```

**Comment by russell-taylor** [comment]
It is true that VRPN connections are not thread-safe, so that if two threads tried to write to them at the same time you would expect errors.  The normal, and safest, approach would be to make each driver single threaded and call all required functions on one at a time, as the standard VRPN server does.

Another approach could be to put a mutex around the vrpn_Connection object that is being used, but I really recommend switching to a single-threaded driver approach because there may be other gotchas.
