### ISSUE TITLE
new 3dconnexion wireless not work

### ISSUE THREAD

**Issue by tufeixp** [vrpn/vrpn#228]
in vrpn_3DConnexion.C modified:
static const vrpn_uint16 vrpn_3DCONNEXION_SPACEMOUSEWIRELESS = 50770;//50735;

XXX Found vendor 0x256f, product 0xc652, interface 4
vrpn_HidInterface::reconnect(): Found 3Dconnexion 3Dconnexion Universal Receiver (256f:c652) at path \\?\hid#vid_256f&pid_c652&mi_04#7&136a194d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} - will attempt to open.
vrpn_HidInterface::reconnect(): Device successfully opened.
vrpn_HidInterface::update(): Read error
vrpn_HidInterface::update(): error message: vrpn: Connection request received from 127.0.0.1: 127.0.0.1 50600

but 
D:\Github\vrpn\build\client_src\Debug>vrpn_print_devices.exe device0@localhost
Opened device0@localhost as: Tracker Button Analog Dial Text.
Press ^C to exit.
Button device0@localhost has 2 buttons with states: 0 0
Button device0@localhost has 2 buttons with states: 0 0

**Comment by russell-taylor** [comment]
Thank you for digging into this!

The client side prints just indicate that the device was created; it presumably is never giving any reports.

The server-side change of ID indicates that there are two wireless versions, one with the old product ID that the code worked with and a new one that it does not work with.  If this new device can be made to work, we'll want to devices, maybe WIRELESS and WIRELESSV2, so that the code will continue to work with the previous version.

The Read error indicates that hid_read() failed on the device.  This would either be because the version of the HIDAPI we're using is incompatible with the device or that the device sends data in a different manner than the other devices.  You might try updating to a newer version of HIDAPI to see if that gets it to start sending data.  If so, then the parsing code may need to change to handle whatever reports the new device can send; this can be done in a new derived class for this device.

**Comment by tufeixp** [comment]
thanks Russell. I've managed to make it work by disabling the redundant hid devices related to 3dconnexion lists under windows device manager: 
-------------------
D:\Github\vrpn\submodules\hidapi\windows\Debug>hidtest.exe
Device Found
Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_03#7&106d2475&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    3

Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_00&col01#7&4bd49ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    0

Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_01#7&1c80d5f2&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    1

Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_02#7&34446237&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    2

Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_00&col02#7&4bd49ad&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    0

Device Found
  type: beef 046d
  path: \\?\hid#3dxkmj_hidmini&col01#1&2d595ca7&2&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: (null)
  Product:      (null)
  Release:      101
  Interface:    -1

Device Found
  type: beef 046d
  path: \\?\hid#3dxkmj_hidmini&col02#1&2d595ca7&2&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: (null)
  Product:      (null)
  Release:      101
  Interface:    -1

Device Found
  type: beef 046d
  path: \\?\hid#3dxkmj_hidmini&col03#1&2d595ca7&2&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: (null)
  Product:      (null)
  Release:      101
  Interface:    -1

Device Found
  type: 256f c652
  path: \\?\hid#vid_256f&pid_c652&mi_00&col03#7&4bd49ad&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
  serial_number: (null)
  Manufacturer: 3Dconnexion
  Product:      3Dconnexion Universal Receiver
  Release:      102
  Interface:    0

unable to open device

----------------------------
looks like the program will intent to find the first device with configured vid&pid, disregard the interface number. Don't know why 3dconnexion implements hid devices with various interfaces, only mi_00 can be read with vrpn.
Then another problem rises, same as mentioned here:https://github.com/vrpn/vrpn/issues/52
-----------server-----------
vrpn_3DConnexion::decodePacket(): Long packet (13 bytes), may mis-parse
-----------client-----------
Analog device0@localhost:
          0.07,  0.12,  0.00,  0.00,  0.00,  0.00 (6 chans)
----------------------
Any solution to parse the 13 bytes packet correctly?

**Comment by msolive1985** [comment]
Thank you so much for the thread. In my case, my 3Dconnexion SpaceMouse Wireless has VID=0x256f and PID=0xc62e. After changing these values in the C file, it started to work.

**Comment by russell-taylor** [comment]
That is the same vendor ID and one lower PID than the code has already.  I wonder if the original was a typo.  Added a vrpn_3DConnexion_SpaceMouseWireless2 device that has the new PID, so that you should be able to use it out of the box and it will still be compatible with an older version with the different PID if these actually exist.

Added in commit bd6520af2eb76b5ee902c23893ea3a4e053741f3
