### ISSUE TITLE
How to interpret the angular velocity provided by the callback?

### ISSUE THREAD

**Issue by francesco-romano** [vrpn/vrpn#260]
Hello.

I am trying to use VRPN to connect to a VICON system, and I am trying to understand how to interpret the angular velocity provided by VRPN.

In https://github.com/vrpn/vrpn/blob/master/vrpn_Tracker.h#L96-L97 it says:

```
vrpn_float64 vel[3], vel_quat[4]; // Cur velocity and dQuat/vel_quat_dt
vrpn_float64 vel_quat_dt;         // delta time (in secs) for vel_quat
```

So clearly this is not an angular velocity, but it is not also a quaternion derivative. 
When trying on a non-moving object I get the following logs (as taken from `vel_quat`):
```
0.000118324, 8.70899e-05, -3.15567e-05, 1, 
-0.000276287, -0.000373585, 0.000170279, 1, 
0.00021985, 0.000333794, -0.000154233, 1, 
-1.47251e-05, 9.83895e-05, 1.81079e-05, 1, 
7.90929e-05, -3.89574e-05, -6.71466e-05, 1, 
3.7941e-05, -4.29377e-05, -1.36023e-05, 1, 
-9.54674e-05, 1.16271e-05, 5.76975e-05, 1, 
9.96428e-05, 0.000188693, -7.55758e-05, 1, 
3.30508e-05, -1.82786e-05, -9.1575e-06, 1, 
-0.000275043, -0.000151221, 0.000188944, 1, 
0.000401624, 0.00032728, -0.000289076, 1, 
-0.000154671, 1.02245e-05, 6.95091e-05, 1, 
0.000373087, 0.000224309, -0.000236311, 1, 
-0.000344439, -0.000311826, 0.00029247, 1, 
```
which seems to be a quaternion. How can I interpret this as an angular velocity?

Also, slightly unrelated question: is the velocity provided by VRPN or by the tracking system, e.g. VICON? I am asking as: i) should I check the definition of the velocity in VICON instead of VRPN? and ii) I will probably try the same code on a couple of other systems and I was curious if I need to check the availability of the velocity or I am always guaranteed this is available.

**Comment by russell-taylor** [comment]
Yeah, the comments are a bit terse.  Because a unit quaternion can only represent rotations of <= 180 degrees but rotational velocity can exceed that in any given time period, the encoding lets the sender set a time period and the amount of rotation during that time period.  To find the rotation per second, you need to multiply the amount of rotation by the inverse of the dt.  You'll need to convert it from unit quaternion form before doing the multiplication to prevent wrapping for fast-rotating objects.

The velocity is provided by the driver, in this case VICON.
- It is not guaranteed to be provided by a given driver, in which case no such callbacks will occur.
- The rate of callbacks for position and velocity are not guaranteed to be the same (though they often are) and timestamps should be used to merge them.
- Trackers do not always provide both position and orientation data, in which case the orientation data should remain fixed at the identity.

**Comment by josechenf** [comment]
Hello,

Thank you. So `vel_quat` is the amount rotation of the object (about the global frame, represented as a unit quaternion) if it were to hold the angular velocity constant for a time period of `vel_quat_dt`.

I'm trying to figure out how this representation would work for the acceleration (i.e. `acc_quat` and `acc_quat_dt`). 
1. Would this be the expected rotation of the object (about the global frame, represented as a unit quaternion) if it were to hold the angular acceleration constant for a time period of `acc_quat_dt` with zero angular velocity? 
2. Or could it assume a non-zero angular velocity?

Thanks

**Comment by russell-taylor** [comment]
vel_quat is the amount of rotation you would get over time interval vel_quat_dt assuming that acc_quat is 0.

I don't think we've seen any drivers that report the rotational acceleration (they do report the positional acceleration, but report the angular as 0).  If you did find one reporting nonzero angular acceleration, acc_quat would be the change in angular velocity over time period acc_quat_dt.
