### ISSUE TITLE
Replace homegrown, duplicated linked lists

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#91]
An easy way to find them is to just search the source for `snitch` and `victim`, which appear to be idiomatic in the linked-list pattern from legacy VRPN code.

**Comment by russell-taylor** [comment]
To prevent conflicts with libraries that use a different flavor of the standard template libraries, we can't #include either set of them (<list> vs. <list.h>).  An earlier attempt to use them ran aground because the SensAble libraries use the list.h and kindred, which is how we ended up with the home-grown version.

Not sure what is wrong with the current code that requires replacement.
