### ISSUE TITLE
Device Repository

### ISSUE THREAD

**Issue by SurfingNerd** [vrpn/vrpn#96]
Hello, is there any repository about supported devices and their channels ?

Actually the only information source seems to be the header files.
i am thinking about a computer readable repository that could simplify some steps.
Example:

		<DeviceDescriptions>
		  <VRPNDevice Name="BalanceBoard"  >
			<VRPNAnalog1D Name="BatteryLevel" Channel="0" MinRange="0" MaxRange="1"/>
			<VRPNAnalog1D Name="TopLeft" Channel="64" MinRange="0" MaxRange="200"/>
			<VRPNAnalog1D Name="TopRight" Channel="65" MinRange="0" MaxRange="200"/>
			<VRPNAnalog1D Name="BottomLeft" Channel="66" MinRange="0" MaxRange="200"/>
			<VRPNAnalog1D Name="BottomRight" Channel="67" MinRange="0" MaxRange="200"/>
			<VRPNAnalog1D Name="TotalMass" Channel="68" MinRange="0" MaxRange="255"/>
			<VRPNAnalog1D Name="AxisX" Channel="70" MinRange="-1" MaxRange="1"/>
			<VRPNAnalog1D Name="AxisY" Channel="70" MinRange="-1" MaxRange="1"/>
		  </VRPNDevice>
		</DeviceDescriptions>

If theres no repository available, i could provide one in future. - because i need that anyway for my project.

**Comment by russell-taylor** [comment]
The OSVR project is providing semantic wrappers for VRPN objects.  If you're going to need fill all this in by hand, I recommend doing it in that project's Json format so that everyone else can use the results.  github.com/OSVR/OSVR-Core is the project repository and osvr.com has pointer to developer info.  Ask on OSVR if it isn't clear how to generate the appropriate file.

**Comment by rpavlik** [comment]
Yeah, that's almost exactly the same data we have for analogs in OSVR. (except we're using JSON and already have a JSON-Schema and browser-based-editor, etc)

**Comment by SurfingNerd** [comment]
ok thank you, i will check this out.
