### ISSUE TITLE
Build fails when vrpn source is in a sym-linked directory

### ISSUE THREAD

**Issue by camerongivler** [vrpn/vrpn#99]
I have vrpn checked out in ~/Documents/aqueti/vrpn, but ~/Documents is a symlink to /mnt/hgfs/UbuntuDocuments (for reasons I won't go into here).

When I do a fresh checkout from vrpn and then (from ~) mkdir build/; cd build; mkdir vrpn; cd vrpn; cmake ~/Documents/aqueti/vrpn; make

Quat builds fine, but there is a problem with the vrpn_Configure.h file.  The message is below, but the basic problem is that the symlink doesn't work right for the make.

In file included from /home/cameron/Documents/aqueti/vrpn/vrpn_BaseClass.h:21:0,
                 from /home/cameron/Documents/aqueti/vrpn/vrpn_Analog.h:6,
                 from /home/cameron/Documents/aqueti/vrpn/vrpn_Analog.C:1:
/home/cameron/Documents/aqueti/vrpn/vrpn_Configure.h:664:26: fatal error: ../../../build/vrpn/vrpn_Configure.h: No such file or directory
 #include VRPN_USING_CMAKE
                          ^
compilation terminated.
make[2]: **\* [CMakeFiles/vrpn.dir/vrpn_Analog.C.o] Error 1
make[1]: **\* [CMakeFiles/vrpn.dir/all] Error 2
make: **\* [all] Error 2

**Comment by russell-taylor** [comment]
Tried to replicate by making ~/test a symlink to /tmp/test, then making ~/test/aqueti/vrpn the clone location and replicating your steps above but things build fine, both if I'm building in ~/build/vrpn and if I'm building in ~/test/build/vrpn.

When I repeated this with ~/Documents, I get the failure described above.  Seems like something magical about Documents.  The same thing happened when I used /home/taylorr/Documents/aqueti/vrpn rather than using ~.

**Comment by russell-taylor** [comment]
It also fails if I build in ~/build (rather than ~/build/vrpn) and point it at ~/test/aqueti/vrpn.  Looks like a level of indirection issue rather than a folder-name issue (in my previous build, where I thought I was at ~/build/vrpn with Documents, I was instead at ~/build).

**Comment by russell-taylor** [comment]
An absolute path to the file seems to work in all cases, where a relative path does not.  Replaced this in 557efa9c2dbed425f579a3c09adc74c6281f886d
